name: Integrity Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run_integrity_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pytest

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/